import { useMemo } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Copy, Download, Cpu, TrendingUp, ShieldCheck, Sparkles } from "lucide-react";
import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { buildDeal } from "@/lib/dealData";
import { toast } from "sonner";

const DealRoom = () => {
  const { bank = "" } = useParams();
  const decoded = decodeURIComponent(bank);
  const deal = useMemo(() => buildDeal(decoded), [decoded]);

  const copyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      toast.success("Deal Room link copied to clipboard");
    } catch {
      toast.error("Could not copy link");
    }
  };

  const exportReport = () => {
    toast.success("Exporting Deal Room as PDF…", { description: "Your download will begin shortly." });
  };

  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader>
        <Button asChild size="sm" variant="ghost">
          <Link to={`/dashboard/${encodeURIComponent(deal.bank)}`}>
            <ArrowLeft className="mr-1.5 h-4 w-4" /> Dashboard
          </Link>
        </Button>
        <Button size="sm" variant="outline" className="border-border/60" onClick={copyLink}>
          <Copy className="mr-1.5 h-4 w-4" /> Copy Link
        </Button>
        <Button size="sm" className="bg-gradient-primary shadow-glow hover:opacity-95" onClick={exportReport}>
          <Download className="mr-1.5 h-4 w-4" /> Export Report
        </Button>
      </AppHeader>

      <main className="flex-1 container max-w-5xl py-12 md:py-16 animate-fade-in">
        {/* Cover */}
        <div className="relative overflow-hidden rounded-3xl border border-border/60 bg-gradient-card p-8 md:p-12 shadow-elegant">
          <div className="pointer-events-none absolute -top-32 -right-32 h-80 w-80 rounded-full bg-primary/20 blur-3xl" />
          <div className="pointer-events-none absolute -bottom-32 -left-32 h-80 w-80 rounded-full bg-accent/20 blur-3xl" />

          <div className="relative">
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              Generated by Blostem Forge
              <span>·</span>
              <span>{new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</span>
            </div>
            <h1 className="mt-4 font-display text-4xl md:text-6xl font-semibold tracking-tight leading-[1.05]">
              The <span className="gradient-text">{deal.bank}</span> opportunity
            </h1>
            <p className="mt-5 max-w-2xl text-base md:text-lg text-muted-foreground">
              An enterprise-grade deal brief covering technical fit, commercial impact and regulatory posture.
            </p>
            <div className="mt-6 flex flex-wrap gap-2">
              <Badge variant="outline" className="border-border/60 text-muted-foreground font-normal">Confidential</Badge>
              <Badge variant="outline" className="border-border/60 text-muted-foreground font-normal">Account team only</Badge>
              <Badge variant="outline" className="border-primary/30 text-primary font-normal bg-primary/5">v1.0</Badge>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <Section title="Executive Summary" eyebrow="01">
          <p className="text-base md:text-lg leading-relaxed text-foreground/90">
            {deal.summary}
          </p>
          <div className="mt-6 grid sm:grid-cols-3 gap-4">
            <Stat label="Estimated ARR" value="₹42 Cr" sub="within 12 months" />
            <Stat label="Conversion lift" value="+18.4%" sub="digital onboarding" />
            <Stat label="Implementation" value="6–8 wks" sub="zero data egress" />
          </div>
        </Section>

        {/* Stakeholders */}
        <Section title="Stakeholder briefs" eyebrow="02">
          <div className="grid md:grid-cols-3 gap-4">
            <StakeholderCard
              icon={Cpu}
              role="CTO"
              tagline="Engineering & infrastructure"
              points={deal.cto.slice(0, 3).map((c) => c.title)}
            />
            <StakeholderCard
              icon={TrendingUp}
              role="Business"
              tagline="Revenue & growth"
              points={deal.business.slice(0, 3).map((b) => b.title)}
            />
            <StakeholderCard
              icon={ShieldCheck}
              role="Compliance"
              tagline="Risk & regulation"
              points={deal.compliance.slice(0, 3).map((c) => c.title)}
            />
          </div>
        </Section>

        {/* Key signals */}
        <Section title="Key signals" eyebrow="03">
          <div className="rounded-2xl border border-border/60 bg-card/60 divide-y divide-border/60 overflow-hidden">
            {deal.signals.map((s) => (
              <div key={s.insight} className="grid grid-cols-12 gap-4 p-5 hover:bg-card transition-colors">
                <div className="col-span-12 md:col-span-3">
                  <div className="text-sm font-medium">{s.source}</div>
                  <div className="text-xs text-muted-foreground">{s.date}</div>
                </div>
                <div className="col-span-12 md:col-span-9 text-sm leading-relaxed text-foreground/90">
                  {s.insight}
                </div>
              </div>
            ))}
          </div>
        </Section>

        {/* CTA Footer */}
        <div className="mt-16 rounded-2xl border border-border/60 bg-gradient-subtle p-8 text-center">
          <h3 className="font-display text-2xl font-semibold">Share this Deal Room with your team</h3>
          <p className="mt-2 text-sm text-muted-foreground max-w-xl mx-auto">
            Anyone with the link can view this brief. Export a PDF for offline review or board prep.
          </p>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <Button variant="outline" className="border-border/60" onClick={copyLink}>
              <Copy className="mr-1.5 h-4 w-4" /> Copy Link
            </Button>
            <Button className="bg-gradient-primary shadow-glow hover:opacity-95" onClick={exportReport}>
              <Download className="mr-1.5 h-4 w-4" /> Export Report
            </Button>
          </div>
        </div>

        <footer className="mt-12 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
          <div>Generated by Blostem Forge · For internal account use only</div>
          <div>© {new Date().getFullYear()} Blostem</div>
        </footer>
      </main>
    </div>
  );
};

const Section = ({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) => (
  <section className="mt-14">
    <div className="flex items-baseline gap-3 mb-5">
      <span className="font-mono text-xs text-primary">{eyebrow}</span>
      <h2 className="font-display text-2xl font-semibold tracking-tight">{title}</h2>
      <div className="flex-1 h-px bg-border/60" />
    </div>
    {children}
  </section>
);

const Stat = ({ label, value, sub }: { label: string; value: string; sub: string }) => (
  <div className="rounded-xl border border-border/60 bg-card/60 p-5">
    <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div>
    <div className="mt-1 font-display text-2xl font-semibold gradient-text">{value}</div>
    <div className="mt-0.5 text-xs text-muted-foreground">{sub}</div>
  </div>
);

const StakeholderCard = ({
  icon: Icon,
  role,
  tagline,
  points,
}: {
  icon: React.ComponentType<{ className?: string }>;
  role: string;
  tagline: string;
  points: string[];
}) => (
  <div className="group relative rounded-2xl border border-border/60 bg-gradient-card p-6 shadow-card hover:border-primary/30 hover:shadow-glow transition-all duration-300">
    <div className="h-10 w-10 rounded-lg bg-primary/10 border border-primary/30 grid place-items-center text-primary mb-4">
      <Icon className="h-4.5 w-4.5" />
    </div>
    <div className="font-display text-lg font-semibold">{role}</div>
    <div className="text-xs text-muted-foreground">{tagline}</div>
    <ul className="mt-4 space-y-2">
      {points.map((p) => (
        <li key={p} className="flex items-start gap-2 text-sm text-foreground/90">
          <span className="mt-2 h-1 w-1 rounded-full bg-primary shrink-0" />
          <span>{p}</span>
        </li>
      ))}
    </ul>
  </div>
);

export default DealRoom;
